name 'linux_patching'
description 'Patches linux servers'
maintainer 'andrew hudson'
maintainer_email 'ahudson@chef.io'
license 'All Rights Reserved'
description 'Tag based linux patching cookbook'
version '0.1.0'
chef_version '>= 13.0'
