---
  driver:
    name: dokken
    chef_version: latest
  
  transport:
    name: dokken
  
  provisioner:
    name: dokken
    deprecations_as_errors: true

  verifier:
    name: inspec
  
  platforms:
  
  - name: centos-7
    driver:
      image: dokken/centos-7
  
  # - name: centos-6
  #   driver:
  #     image: dokken/centos-6
  
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
  
  # - name: ubuntu-14.04
  #   driver:
  #     image: dokken/ubuntu-14.04

  suites:
    - name: default
      # data_bags_path: "../../data_bags"
      run_list:
        - recipe[linux_repository::default]
