name 'linux_repository'
description 'Creates linux repository files'
maintainer 'Andrew Hudson'
maintainer_email 'ahudson@chef.io'
license 'All Rights Reserved'
version '0.1.0'
chef_version '>= 13.0'
